version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: go_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: go_postgres
      POSTGRES_PASSWORD: go_postgres
      POSTGRES_DB: go_postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
